// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/groups/:groupId": {
    params: {
      "groupId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/notifications" | "/dashboard" | "/groups/:groupId";
  };
  "./pages/Landing.jsx": {
    id: "pages/Landing";
    page: "/";
  };
  "./features/auth/Login.jsx": {
    id: "features/auth/Login";
    page: "/login";
  };
  "./features/auth/Register.jsx": {
    id: "features/auth/Register";
    page: "/register";
  };
  "./pages/Notifications.jsx": {
    id: "pages/Notifications";
    page: "/notifications";
  };
  "./components/common/ProtectedLayout.jsx": {
    id: "components/common/ProtectedLayout";
    page: "/dashboard" | "/groups/:groupId";
  };
  "./pages/Dashboard.jsx": {
    id: "pages/Dashboard";
    page: "/dashboard";
  };
  "./features/groups/GroupDetails.jsx": {
    id: "features/groups/GroupDetails";
    page: "/groups/:groupId";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Landing": typeof import("./src/./pages/Landing.jsx");
  "features/auth/Login": typeof import("./src/./features/auth/Login.jsx");
  "features/auth/Register": typeof import("./src/./features/auth/Register.jsx");
  "pages/Notifications": typeof import("./src/./pages/Notifications.jsx");
  "components/common/ProtectedLayout": typeof import("./src/./components/common/ProtectedLayout.jsx");
  "pages/Dashboard": typeof import("./src/./pages/Dashboard.jsx");
  "features/groups/GroupDetails": typeof import("./src/./features/groups/GroupDetails.jsx");
};